### ISSUE TITLE
NHK - On Demand Error

### ISSUE THREAD

**Issue by Andulien** [misty-/addons#4]
It seems that on the NHK Plugin the "NHK World On Demand" Section is not working at all anymore. Meaning when I click on the Menu Item it just says to check the error log and does not open. Maybe the link is outdated?
Thanks for looking into this.

**Comment by Andulien** [comment]
11:24:01 T:4504  NOTICE: ES: Client  from 127.0.0.1 timed out
11:24:32 T:3324   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\MCramer\AppData\Roaming\Kodi\addons\plugin.video.bestofnhk\default.py", line 666, in <module>
                                                IDX_VOD(url)
                                              File "C:\Users\MCramer\AppData\Roaming\Kodi\addons\plugin.video.bestofnhk\default.py", line 254, in IDX_VOD
                                                vod_json = json.load(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json__init__.py", line 290, in load
                                                **kw)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
11:24:32 T:5920   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.bestofnhk/?mode=vod&name=NHK%20World%20On%20Demand&url=http%3a%2f%2fwww3.nhk.or.jp%2fnhkworld%2fen%2fvod%2fvod_episodes.xml
11:24:32 T:5920   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bestofnhk/?mode=vod&name=NHK%20World%20On%20Demand&url=http%3a%2f%2fwww3.nhk.or.jp%2fnhkworld%2fen%2fvod%2fvod_episodes.xml) failed

**Comment by misty-** [comment]
The issue is resolved in the latest releases. Issue closed.

**Comment by Andulien** [comment]
Issue is still existing. 

20:10:25 T:5072  NOTICE: Checking resolution 16
20:10:26 T:5072  NOTICE: Running database version Addons20
20:10:26 T:5072  NOTICE: Running database version ViewModes6
20:10:26 T:5072  NOTICE: Running database version Textures13
20:10:26 T:5072  NOTICE: Running database version MyMusic56
20:10:26 T:5072  NOTICE: Running database version MyVideos99
20:10:26 T:5072  NOTICE: Running database version TV29
20:10:26 T:5072  NOTICE: Running database version Epg11
20:10:26 T:5072 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
20:10:26 T:2900  NOTICE: PVRManager - starting up
20:10:26 T:5072  NOTICE: ActiveAE DSP - starting
20:10:26 T:5072  NOTICE: initialize done
20:10:26 T:5072  NOTICE: Running the application...
20:10:26 T:5072  NOTICE: starting zeroconf publishing
20:10:26 T:5072  NOTICE: WebServer: Started the webserver
20:10:26 T:5072  NOTICE: starting upnp client
20:10:26 T:1412  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
20:10:26 T:1412  NOTICE: UDP: Listening on port 9777
20:10:29 T:4756  NOTICE: script.grab.fanart: Grab Fanart Service Started
20:10:30 T:3180  NOTICE: script.module.youtube.dl: youtube_dl core version: 2016.05.21.2
20:10:30 T:3180  NOTICE: version 4.6.1 started
20:10:31 T:1092  NOTICE: script.module.youtube.dl: youtube_dl core version: 2016.05.21.2
20:10:32 T:1092  NOTICE: Previous line repeats 1 times.
20:10:32 T:1092  NOTICE: version 4.6.1 started
20:10:33 T:1092  NOTICE: Previous line repeats 1 times.
20:10:33 T:1092 WARNING: Attempt to use invalid handle 5
20:10:33 T:1092 WARNING: Previous line repeats 29 times.
20:10:33 T:1092  NOTICE: finished
20:10:33 T:3180 WARNING: Attempt to use invalid handle 3
20:10:33 T:3180 WARNING: Previous line repeats 29 times.
20:10:33 T:3180  NOTICE: finished
20:10:34 T:4768  NOTICE: Previous line repeats 1 times.
20:10:34 T:4768  NOTICE: script.module.youtube.dl: youtube_dl core version: 2016.05.21.2
20:10:34 T:4768  NOTICE: version 4.6.1 started
20:10:34 T:4196  NOTICE: EPG::CEpgContainer::Start - EPG thread started
20:10:34 T:4768 WARNING: Attempt to use invalid handle 6
20:10:34 T:4768 WARNING: Previous line repeats 29 times.
20:10:34 T:4768  NOTICE: finished
20:10:42 T:1304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\MCramer\AppData\Roaming\Kodi\addons\plugin.video.bestofnhk\default.py", line 722, in <module>
                                                IDX_VOD(url)
                                              File "C:\Users\MCramer\AppData\Roaming\Kodi\addons\plugin.video.bestofnhk\default.py", line 254, in IDX_VOD
                                                vod_json = json.load(req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json__init__.py", line 290, in load
                                                **kw)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 366, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 384, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
20:10:42 T:5072   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.bestofnhk/?mode=vod&name=NHK%20World%20On%20Demand&url=http%3a%2f%2fwww3.nhk.or.jp%2fnhkworld%2fen%2fvod%2fvod_episodes.xml
20:10:42 T:5072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bestofnhk/?mode=vod&name=NHK%20World%20On%20Demand&url=http%3a%2f%2fwww3.nhk.or.jp%2fnhkworld%2fen%2fvod%2fvod_episodes.xml) failed
